version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # Group minor and patch updates together (usually low risk)
      non-breaking:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

      # Keep major version updates in their own separate group
      breaking:
        patterns:
          - "*"
        update-types:
          - "major"
